# -*- coding: utf-8 -*-
"""Commit8_langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLsukB_rrFoElKUS_VsSJNLksTz7vOtM

# Campus Query Agent — ReAct + Sitemap Architecture

```
ONE TIME per college
  build_sitemap()  crawls 2 levels (HTTP only, no LLM)
                   LLM classifies all links into topic map  (1 LLM call)
                   saves sitemap_{domain}.json to disk

PER QUERY
  ReAct Agent      lookup_sitemap(topic)   reads disk, free
                   fetch_page(url)         cached HTTP
                   get_page_links(url)     cached HTTP
                   read_pdf(url)           HTTP + pypdf
                   agent reasons until it has enough to answer
```
The agent decides its own navigation path. No hardcoded crawl logic.
"""

# Cell 1 - Install
!pip install langchain langchain-google-genai langchain-community langgraph beautifulsoup4 requests pypdf gradio

# Cell 2 - Imports
import io
import json
import logging
import os
from datetime import datetime
from urllib.parse import urljoin, urlparse
from typing import List, Optional

import requests
from bs4 import BeautifulSoup
from pypdf import PdfReader
from IPython.display import Markdown, display

logging.getLogger('pypdf').setLevel(logging.ERROR)

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.tools import tool
from langchain_core.prompts import ChatPromptTemplate, SystemMessagePromptTemplate, HumanMessagePromptTemplate
from langchain_core.output_parsers import PydanticOutputParser, StrOutputParser
from langchain_core.messages import SystemMessage, HumanMessage
from langgraph.prebuilt import create_react_agent
from pydantic import BaseModel, Field

# Cell 3 - API Key
from google.colab import userdata
os.environ['GOOGLE_API_KEY'] = userdata.get('Gemini1')

# Cell 4 - LLM
# One model used for sitemap building AND ReAct agent reasoning.
llm = ChatGoogleGenerativeAI(
    model='gemini-2.5-flash-lite',
    temperature=0
)

# Cell 5 - Raw Web Scraping Utilities
# Plain Python helpers - NOT tools.
# The @tool wrappers in Cell 9 call these internally.

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                  'AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/117.0.0.0 Safari/537.36'
}

def _raw_fetch_text(url: str) -> str:
    """Download a page and return its visible text."""
    r = requests.get(url, headers=HEADERS, timeout=10)
    r.raise_for_status()
    return BeautifulSoup(r.text, 'html.parser').get_text(separator=' ', strip=True)

def _raw_fetch_links(url: str) -> list:
    """
    Download a page and return all links as dicts with keys: href, abs_url, text.
    Skips anchors, mailto, tel, javascript links.
    Resolves relative hrefs to absolute URLs.
    """
    r = requests.get(url, headers=HEADERS, timeout=10)
    r.raise_for_status()
    soup = BeautifulSoup(r.content, 'html.parser')
    results = []
    for a in soup.find_all('a', href=True):
        href = a['href'].strip()
        if not href or href.startswith(('#', 'mailto:', 'tel:', 'javascript:')):
            continue
        abs_url = urljoin(url, href)
        text = a.get_text(separator=' ', strip=True)
        results.append({'href': href, 'abs_url': abs_url, 'text': text})
    return results

def _same_domain(base_url: str, target_url: str) -> bool:
    """Return True if target_url is on the same domain as base_url."""
    return urlparse(base_url).netloc == urlparse(target_url).netloc

def _extract_pdf_text(pdf_url: str, max_pages: int = 10) -> str:
    """Download a PDF and extract text from its first max_pages pages."""
    r = requests.get(pdf_url, headers=HEADERS, timeout=15)
    r.raise_for_status()
    reader = PdfReader(io.BytesIO(r.content))
    return '\n'.join(p.extract_text() or '' for p in reader.pages[:max_pages]).strip()

# Cell 6 - Disk Cache
# Page text cache + sitemap store, both survive Colab kernel restarts.

PAGE_CACHE_FILE = '/content/page_cache.json'
_page_cache: dict = {}

def _load_page_cache():
    global _page_cache
    if os.path.exists(PAGE_CACHE_FILE):
        with open(PAGE_CACHE_FILE) as f:
            _page_cache = json.load(f)

def _save_page_cache():
    with open(PAGE_CACHE_FILE, 'w') as f:
        json.dump(_page_cache, f, indent=2)

def cached_page(url: str) -> str:
    """Return cached page text, or fetch-and-cache it if not seen before."""
    if url not in _page_cache:
        print(f'    [HTTP  ] {url}')
        _page_cache[url] = _raw_fetch_text(url)
        _save_page_cache()
    else:
        print(f'    [cache ] {url}')
    return _page_cache[url]

def _sitemap_path(domain: str) -> str:
    return f"/content/sitemap_{domain.replace('.', '_')}.json"

def _load_sitemap(domain: str) -> Optional[dict]:
    path = _sitemap_path(domain)
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return None

def _save_sitemap(domain: str, sitemap: dict):
    with open(_sitemap_path(domain), 'w') as f:
        json.dump(sitemap, f, indent=2)

def clear_cache():
    """Wipe the page cache and all sitemaps."""
    global _page_cache
    _page_cache = {}
    files_to_remove = [PAGE_CACHE_FILE] + [
        os.path.join('/content', f)
        for f in os.listdir('/content')
        if f.startswith('sitemap_') and f.endswith('.json')
    ]
    for f in files_to_remove:
        if os.path.exists(f):
            os.remove(f)
    print('All caches cleared.')

_load_page_cache()

# Cell 7 - Pydantic Schema for Sitemap Builder output

class SitemapEntry(BaseModel):
    topic: str = Field(
        description='Topic category e.g. transport, placements, hostel, academics, fees, admissions, facilities, research, about, events'
    )
    label: str = Field(description='Human-readable label for this link e.g. Bus Routes Page')
    url:   str = Field(description='Full absolute URL')
    kind:  str = Field(description='Either page or pdf')

class CollegeSitemap(BaseModel):
    entries: List[SitemapEntry] = Field(description='All classified links from the college site')

# Cell 8 - Sitemap Builder
#
# Cost: exactly 1 LLM call per college, no matter how many queries follow.
#
# Steps:
#   1. Fetch homepage, collect all links with anchor text  (HTTP, no LLM)
#   2. Follow each same-domain sub-page, collect its links too  (HTTP, no LLM)
#   3. Send full deduplicated link list to LLM for topic classification  (1 LLM call)
#   4. Save result as sitemap_{domain}.json

sitemap_parser = PydanticOutputParser(pydantic_object=CollegeSitemap)

sitemap_prompt = ChatPromptTemplate.from_messages([
    SystemMessagePromptTemplate.from_template(
        'You are building a topic map of a college website.\n'
        'Given a list of links (anchor text | URL), classify each informational link into a topic.\n'
        'Topics: transport, placements, hostel, academics, fees, admissions, facilities, research, about, events, other.\n'
        'Skip: navigation links, login, search, social media, external sites, duplicate entries.\n'
        'For PDFs set kind=pdf, for pages set kind=page.\n'
        'Respond ONLY with valid JSON matching this schema:\n'
        '{format_instructions}'
    ),
    HumanMessagePromptTemplate.from_template(
        'College: {college_name}\n'
        'Base URL: {base_url}\n\n'
        'Links found across the site (anchor text | full URL):\n'
        '{links_text}'
    )
])

sitemap_chain = sitemap_prompt | llm | sitemap_parser


def build_sitemap(college_name: str, base_url: str) -> str:
    """
    Crawl the college site 2 levels deep, classify all links into a topic map,
    and save to disk. Run ONCE per college before asking questions.
    """
    domain = urlparse(base_url).netloc
    print(f'\nBuilding sitemap for {college_name} ({domain})...')

    # Level 0: homepage links
    print('  [Level 0] Fetching homepage links...')
    try:
        homepage_links = _raw_fetch_links(base_url)
    except Exception as e:
        return f'Error fetching homepage: {e}'

    # Level 1: follow same-domain sub-pages from homepage
    all_links = list(homepage_links)
    visited = {base_url}
    sub_pages = [
        lnk for lnk in homepage_links
        if _same_domain(base_url, lnk['abs_url'])
        and not lnk['abs_url'].lower().endswith('.pdf')
        and lnk['abs_url'] not in visited
    ][:25]  # cap at 25 to keep cost predictable

    for lnk in sub_pages:
        sub_url = lnk['abs_url']
        visited.add(sub_url)
        try:
            sub_links = _raw_fetch_links(sub_url)
            all_links.extend(sub_links)
            print(f'    [Level 1] {sub_url} -> {len(sub_links)} links')
        except Exception:
            pass

    # Deduplicate, keep same-domain only, resolve to absolute
    seen_urls = set()
    unique_links = []
    for lnk in all_links:
        abs_url = lnk['abs_url']
        if abs_url in seen_urls or not _same_domain(base_url, abs_url):
            continue
        seen_urls.add(abs_url)
        label = lnk['text'] or abs_url.split('/')[-1] or abs_url
        unique_links.append({'label': label, 'url': abs_url})

    print(f'  {len(unique_links)} unique links collected. Classifying with LLM...')

    # Send to LLM for classification (1 LLM call)
    links_text = '\n'.join(
        f"{lnk['label']} | {lnk['url']}"
        for lnk in unique_links[:80]  # cap to stay within token budget
    )
    try:
        result = sitemap_chain.invoke({
            'college_name': college_name,
            'base_url': base_url,
            'links_text': links_text,
            'format_instructions': sitemap_parser.get_format_instructions()
        })
    except Exception as e:
        return f'LLM classification failed: {e}'

    # Organise into topic -> [entries] dict
    topics: dict = {}
    for entry in result.entries:
        t = entry.topic.lower()
        if t not in topics:
            topics[t] = []
        topics[t].append({'label': entry.label, 'url': entry.url, 'kind': entry.kind})

    sitemap = {
        'college_name': college_name,
        'base_url': base_url,
        'built_at': datetime.now().isoformat(),
        'topics': topics
    }

    _save_sitemap(domain, sitemap)

    summary = f'Sitemap built for {college_name}.\n'
    summary += f'Topics found: {list(topics.keys())}\n'
    summary += f'Total entries: {sum(len(v) for v in topics.values())}'
    print(summary)
    return summary

# Cell 9 - Tool Registry
#
# The 4 tools the ReAct agent can call.
# The docstring on each @tool IS the agent's instruction for when to use it.
# Write docstrings as commands to the agent, not as developer comments.

# Holds the sitemap for the college currently being queried.
# Set by create_query() before invoking the agent.
_active_sitemap: dict = {}


@tool
def lookup_sitemap(topic: str) -> str:
    """
    Look up the pre-built college sitemap to find pages and PDFs for a given topic.
    ALWAYS call this tool FIRST. Do not call fetch_page before calling this.
    Input: a single topic word such as transport, placements, hostel, fees, academics.
    Returns: labelled URLs classified under that topic, or the full sitemap if no match.
    """
    if not _active_sitemap:
        return (
            'No sitemap loaded. Navigate manually: '
            'call get_page_links on the base URL to discover the site structure.'
        )

    topics = _active_sitemap.get('topics', {})
    topic_lower = topic.lower()

    # Exact or partial topic match
    matched = []
    for t, entries in topics.items():
        if topic_lower in t or t in topic_lower:
            for e in entries:
                matched.append(f"[{e['kind'].upper()}] {e['label']} -> {e['url']}")

    if matched:
        return f"Found {len(matched)} entries for '{topic}':\n" + '\n'.join(matched)

    # No match - return full sitemap so agent can choose best topic
    lines = [f"No match for '{topic}'. Full sitemap:"]
    for t, entries in topics.items():
        lines.append(f'\n[{t.upper()}]')
        for e in entries[:5]:  # max 5 per topic to avoid flooding context
            lines.append(f"  {e['kind'].upper()} | {e['label']} -> {e['url']}")
    return '\n'.join(lines)


@tool
def fetch_page(url: str) -> str:
    """
    Fetch the visible text content of a college webpage.
    Use this after lookup_sitemap returns a relevant page URL.
    Results are cached - repeated calls to the same URL are free.
    Returns up to 4000 characters of page text.
    """
    try:
        return cached_page(url)[:4000]
    except Exception as e:
        return f'Error fetching {url}: {e}'


@tool
def get_page_links(url: str) -> str:
    """
    Get all links on a page as Anchor Text -> URL pairs.
    Use this to discover deeper pages or find PDF links the sitemap may have missed.
    Only returns links within the same college domain.
    Returns up to 40 links.
    """
    try:
        links = _raw_fetch_links(url)
        lines = [
            f"{lnk['text'] or '(no text)'} -> {lnk['abs_url']}"
            for lnk in links
            if _same_domain(url, lnk['abs_url'])
        ]
        lines = list(dict.fromkeys(lines))[:40]  # deduplicate
        return '\n'.join(lines) if lines else 'No same-domain links found on this page.'
    except Exception as e:
        return f'Error getting links from {url}: {e}'


@tool
def read_pdf(url: str) -> str:
    """
    Download and extract text from a PDF document.
    Use this when lookup_sitemap or get_page_links reveals a PDF that likely
    contains the answer such as bus schedules, placement reports, fee structures.
    Returns up to 3000 characters of extracted text.
    """
    try:
        text = _extract_pdf_text(url)
        return text[:3000] if text else 'PDF appears to be empty or image-only.'
    except Exception as e:
        return f'Error reading PDF {url}: {e}'


# Tool registry passed to the agent
TOOLS = [lookup_sitemap, fetch_page, get_page_links, read_pdf]
print(f'Tools registered: {[t.name for t in TOOLS]}')

# Cell 10 - ReAct Agent
#
# create_react_agent builds a LangGraph state machine that loops:
#   LLM reasons -> picks a tool -> tool executes -> LLM sees result -> reasons again
# until the LLM has enough information to produce a final answer.
#
# The system prompt is the agent's instruction manual.
# It defines: tool order, rules, answer format.

AGENT_SYSTEM_PROMPT = (
    'You are a Campus Query Agent that answers student questions about colleges and universities.\n'
    'You have a pre-built sitemap and four tools to navigate the college website.\n'
    '\n'
    'TOOL ORDER - always follow this sequence:\n'
    '1. lookup_sitemap(topic) - extract the core topic from the query and call this FIRST.\n'
    '2. fetch_page(url) - fetch the most relevant page the sitemap returned.\n'
    '3. get_page_links(url) - if you need to go deeper or find a PDF, get links from that page.\n'
    '4. read_pdf(url) - if a PDF is found that likely has the answer, read it.\n'
    '5. Answer with a clear, concise markdown response once you have enough information.\n'
    '\n'
    'RULES:\n'
    '- Never guess. Only answer from what the tools actually return.\n'
    '- If no sitemap match, call get_page_links on the college base URL to navigate manually.\n'
    '- After 4 tool calls with no relevant result, say so and suggest where to look on the site.\n'
    '- Format your final answer in clean markdown.\n'
)

# Build the agent graph once - stateless and reusable across all queries
agent_graph = create_react_agent(llm, TOOLS)
print('ReAct agent ready.')

# Cell 11 - Pipeline

def create_query(college_name: str, url: str, query: str) -> str:
    """
    Answer a student query about a college using the ReAct agent.

    LLM calls per query:
      Each reasoning step = 1 LLM call (tool selection + observation)
      Typical: 3-5 LLM calls total depending on how deep the agent navigates
    """
    global _active_sitemap

    print(f"\n{'='*60}")
    print(f'Query   : {query}')
    print(f'College : {college_name} ({url})')
    print('='*60)

    # Load sitemap for this college
    domain = urlparse(url).netloc
    sitemap = _load_sitemap(domain)
    if sitemap:
        _active_sitemap = sitemap
        print(f"  Sitemap loaded: topics = {list(sitemap['topics'].keys())}")
    else:
        _active_sitemap = {}
        print('  No sitemap found. Build one first with build_sitemap() for best results.')
        print('  Agent will navigate manually using get_page_links.')

    # Compose the user message with college context
    user_message = (
        f'College: {college_name}\n'
        f'Website: {url}\n'
        f'Query: {query}'
    )

    # Run the ReAct agent
    print('\n[Agent running...]')
    result = agent_graph.invoke({
        'messages': [
            SystemMessage(content=AGENT_SYSTEM_PROMPT),
            HumanMessage(content=user_message)
        ]
    })

    # Print agent trace (tool calls and result previews)
    print('\n[Agent trace]')
    tool_call_count = 0
    for msg in result['messages'][2:]:  # skip system + human
        if hasattr(msg, 'tool_calls') and msg.tool_calls:
            for tc in msg.tool_calls:
                tool_call_count += 1
                print(f'  [{tool_call_count}] CALL   {tc["name"]}({tc["args"]})')
        elif type(msg).__name__ == 'ToolMessage':
            preview = (msg.content or '')[:100].replace('\n', ' ')
            print(f'      RESULT {preview}...')

    print(f'\n  Total tool calls: {tool_call_count}')

    # Last message is always the final answer
    return result['messages'][-1].content

# Cell 12 - Build the sitemap (run once per college)
status = build_sitemap('ANITS', 'https://anits.org/')
print(status)

# Cell 13 - Ask a question
answer = create_query('ANITS', 'https://anits.org/', 'What are the placement statistics?')
display(Markdown(answer))

# Cell 14 - Gradio UI
import gradio as gr

def gradio_build_sitemap(college_name: str, url: str) -> str:
    if not college_name.strip() or not url.strip():
        return 'Please enter both college name and URL.'
    return build_sitemap(college_name.strip(), url.strip())

def gradio_ask(college_name: str, url: str, query: str) -> str:
    if not college_name.strip() or not url.strip() or not query.strip():
        return 'Please fill in all three fields.'
    return create_query(college_name.strip(), url.strip(), query.strip())

with gr.Blocks(title='Campus Query Agent', theme=gr.themes.Soft()) as demo:
    gr.Markdown('# Campus Query Agent')
    gr.Markdown(
        '**Step 1:** Build the sitemap once per college (1 LLM call, saved to disk).  \n'
        '**Step 2:** Ask any question - the agent navigates directly to the right page.'
    )

    with gr.Row():
        college_name = gr.Textbox(label='College Name', placeholder='ANITS')
        college_url  = gr.Textbox(label='Website URL',  placeholder='https://anits.org/')

    with gr.Row():
        build_btn = gr.Button('Build Sitemap',  variant='secondary')
        clear_btn = gr.Button('Clear Cache',    variant='secondary')

    sitemap_status = gr.Textbox(
        label='Sitemap Status',
        value='No sitemap built yet.',
        interactive=False
    )

    gr.Markdown('---')

    user_query = gr.Textbox(
        label='Your Query',
        placeholder='e.g. What are the bus routes?'
    )
    ask_btn = gr.Button('Ask Agent', variant='primary')
    output  = gr.Markdown(value='_Your answer will appear here..._')

    build_btn.click(fn=gradio_build_sitemap, inputs=[college_name, college_url], outputs=sitemap_status)
    clear_btn.click(fn=lambda: (clear_cache(), 'Cache cleared.')[1], outputs=sitemap_status)
    ask_btn.click(fn=gradio_ask, inputs=[college_name, college_url, user_query], outputs=output)

    gr.Examples(
        examples=[
            ['ANITS',      'https://anits.org/',       'What are the transportation routes?'],
            ['ANITS',      'https://anits.org/',       'What are the placement statistics?'],
            ['ANITS',      'https://anits.org/',       'What hostel facilities are available?'],
            ['IIT Bombay', 'https://www.iitb.ac.in/',  'What are the admission requirements?'],
        ],
        inputs=[college_name, college_url, user_query]
    )

if __name__ == '__main__':
    demo.launch()